---
name: _generate
description: |
  **Triggering this workflow directly is only useful for debugging. Most cases
  should use the `benchmark` workflow.**

  This workflow reads the `.json` files created in the `_benchmark` workflow and
  creates derived tables and plots, as well as master indices of the results.

"on":
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      force:
        description: "Regenerate all of the derived data, even if it already exists"
        type: boolean
        default: false
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  generate-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: install dependencies
        run:
          python -m pip install -r requirements.txt
      - name: regenerate
        run:
          python scripts/generate_results.py ${{ inputs.force == true && '--force' || '' }}
      - name: Add to repo
        uses: EndBug/add-and-commit@v9
        if: ${{ !inputs.dry_run }}
        with:
          add: "['results', 'README.md']"
          message: Benchmarking results for @${{ github.actor }}
