---
name: _publish

"on":
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      force:
        description: "Regenerate all of the derived data, even if it already exists"
        type: boolean
        default: false
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - uses: actions/checkout@v3
        with:
          repository: faster-cpython/ideas
          path: public
          ref: main
          token: ${{ secrets.BENCHMARK_PUBLISH }}
      - name: Install dependencies
        run:
          python -m pip install -r requirements.txt
      - name: Copy publishable files
        run: |
          python scripts/publish.py results public/results
      - name: Regenerate derived results and tables
        run: |
          python scripts/generate_results.py public ${{ inputs.force == true && '--force' || '' }}
      - name: Add to repository
        uses: EndBug/add-and-commit@v9
        if: ${{ !inputs.dry_run }}
        with:
          add: "['results', 'README.md']"
          cwd: public

  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: private
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          path: public
          repository: faster-cpython/benchmarking-public
          token: ${{ secrets.BENCHMARK_MIRROR }}
      - name: Mirror
        run: |
          cd public
          git remote add upstream $PWD/../private
          git fetch upstream
          git reset --hard upstream/main
          git push origin main
